spring.application.name=oraclequantapi

# Oracle XE connection ? update username/password to match yours
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=29999login
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate ? auto creates the table on first run
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

server.port