ALTER SESSION SET CONTAINER = XEPDB1;
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER pkc_user IDENTIFIED BY pkc_password';
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, DBA TO pkc_user';
  EXECUTE IMMEDIATE 'ALTER USER pkc_user QUOTA UNLIMITED ON USERS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1920 THEN
      NULL;
    ELSE
      RAISE;
    END IF;
END;
/
