package com.oraclequantapi.oraclequantapi.service;

import com.oraclequantapi.oraclequantapi.model.HistoryRecord;
import com.oraclequantapi.oraclequantapi.repository.HistoryRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Service
@RequiredArgsConstructor
@Slf4j
/**
 * Business logic for conversion history.
 *
 * This service is the middle layer between web controllers and the database
 * repository. Controllers call this class instead of talking to the database
 * directly.
 */
public class HistoryService {

    // Repository is the database helper generated by Spring Data JPA.
    private final HistoryRepository repository;

    /**
     * Creates and saves one history row after a conversion request is handled.
     */
    @Transactional
    public HistoryRecord save(String input, String output, String sourceIpAddress) {
        log.info("Saving history record for input={}, ip={}", input, sourceIpAddress);
        HistoryRecord record = new HistoryRecord();
        record.setTimestamp(LocalDateTime.now());
        record.setInput(input);
        record.setOutput(output);
        record.setSourceIpAddress(sourceIpAddress);
        return repository.save(record);
    }

    /**
     * Reads all saved conversion history rows.
     *
     * readOnly tells Spring this method only reads data and does not change it.
     */
    @Transactional(readOnly = true)
    public List<HistoryRecord> getAll() {
        log.info("Fetching all history records");
        return repository.findAll();
    }

    /**
     * Reads one history row by id.
     *
     * Optional means the result may be empty if the id is not found.
     */
    @Transactional(readOnly = true)
    public Optional<HistoryRecord> getById(Long id) {
        log.info("Fetching history record by id={}", id);
        return repository.findById(id);
    }

    /**
     * Updates the main editable fields of one history row.
     */
    @Transactional
    public HistoryRecord update(Long id, HistoryRecord updated) {
        log.info("Updating history record id={}", id);
        HistoryRecord existing = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("History record not found with id: " + id));
        existing.setInput(updated.getInput());
        existing.setOutput(updated.getOutput());
        return repository.save(existing);
    }

    /**
     * Updates only the fields provided by the request.
     *
     * For example, if the request body contains only "input", output is kept as it was.
     */
    @Transactional
    public HistoryRecord partialUpdate(Long id, Map<String, Object> updates) {
        log.info("Partial updating history record id={}", id);
        HistoryRecord existing = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("History record not found with id: " + id));
        updates.forEach((key, value) -> {
            if ("input".equals(key)) {
                existing.setInput((String) value);
            } else if ("output".equals(key)) {
                existing.setOutput((String) value);
            }
        });
        return repository.save(existing);
    }

    /**
     * Deletes every history row from the database.
     */
    @Transactional
    public void deleteAll() {
        log.info("Deleting all history records");
        repository.deleteAll();
    }
}
