-- Use this file ONLY if XEPDB1 does not exist (Oracle Database 23c Free on Mac).
-- Run as SYSTEM with Service name = FREEPDB1

ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER pkc_user CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1918, -01918) THEN
      RAISE;
    END IF;
END;
/

CREATE USER pkc_user IDENTIFIED BY PkcPassword1
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CONNECT, RESOURCE TO pkc_user;
GRANT CREATE TABLE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO pkc_user;

SELECT privilege FROM dba_sys_privs WHERE grantee = 'PKC_USER';
COMMIT;
