#!/bin/bash
# =============================================================================
# Oracle Linux — full setup for alharith@AlharithLinux VM
# Run on the VM:  bash oracle-linux-all-in-one.sh
# =============================================================================

set -u

LINUX_USER="${LINUX_USER:-alharith}"
HOME_DIR="/home/${LINUX_USER}"
JAR="${HOME_DIR}/pkc-api.jar"
LOG="${HOME_DIR}/pkc-api.out"
ORACLE_SERVICE="${ORACLE_SERVICE:-XEPDB1}"
ORACLE_USER="${ORACLE_USER:-pkc_user}"
ORACLE_PASSWORD="${ORACLE_PASSWORD:-PkcPassword1}"
ORACLE_JDBC_URL="jdbc:oracle:thin:@//localhost:1521/${ORACLE_SERVICE}"
API_PORT="${PORT:-8081}"

echo "=============================================="
echo " PKC-API Oracle Linux setup"
echo " User: ${LINUX_USER}  Service: ${ORACLE_SERVICE}"
echo "=============================================="

# --- 1) Java ---
if ! command -v java &>/dev/null; then
  echo "[1] Installing Java 17..."
  sudo dnf install -y java-17-openjdk-devel || sudo yum install -y java-17-openjdk-devel
fi
echo "[1] Java: $(java -version 2>&1 | head -1)"

# --- 2) JAR ---
if [[ ! -f "${JAR}" ]]; then
  echo "[2] ERROR: Missing ${JAR}"
  echo "    Copy from Mac:"
  echo "    scp /Users/mac/IdeaProjects/oraclequantapi/target/pkc-api.jar ${LINUX_USER}@<VM_HOST>:${JAR}"
  exit 1
fi
echo "[2] JAR OK: $(ls -lh "${JAR}" | awk '{print $5, $9}')"

# --- 3) Oracle listener ---
echo "[3] Checking Oracle listener..."
if command -v lsnrctl &>/dev/null; then
  lsnrctl status | head -20 || true
else
  echo "    lsnrctl not in PATH (Oracle may still run)"
fi

# --- 4) Database user + table ---
SETUP_SQL="${HOME_DIR}/oracle-linux-setup.sql"
cat > "${SETUP_SQL}" <<'SQL'
ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER pkc_user CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1918, -01918) THEN RAISE; END IF;
END;
/

CREATE USER pkc_user IDENTIFIED BY PkcPassword1
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CONNECT, RESOURCE TO pkc_user;
GRANT CREATE TABLE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO pkc_user;

ALTER SESSION SET CURRENT_SCHEMA = pkc_user;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE measurement_history CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE measurement_history (
  id                NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp         TIMESTAMP NOT NULL,
  source_ip_address VARCHAR2(255) NOT NULL,
  input_value       VARCHAR2(4000) NOT NULL,
  output_value      VARCHAR2(4000) NOT NULL
);

SELECT privilege FROM dba_sys_privs WHERE grantee = 'PKC_USER' ORDER BY privilege;
COMMIT;
SQL

# Allow FREEPDB1
if [[ "${ORACLE_SERVICE}" == "FREEPDB1" ]]; then
  sed -i 's/XEPDB1/FREEPDB1/g' "${SETUP_SQL}"
fi

SQLPLUS=""
for p in $(find /opt /u01 /home/oracle 2>/dev/null -name sqlplus -type f 2>/dev/null); do
  SQLPLUS="$p"
  break
done
[[ -z "${SQLPLUS}" ]] && command -v sqlplus &>/dev/null && SQLPLUS="sqlplus"

echo "[4] Database setup..."
if [[ -n "${SQLPLUS}" ]]; then
  if [[ -z "${ORACLE_SYSTEM_PASSWORD:-}" ]]; then
    echo "    Enter SYSTEM password for Oracle (install password):"
    read -rs ORACLE_SYSTEM_PASSWORD
    echo
  fi
  echo "${ORACLE_SYSTEM_PASSWORD}" | "${SQLPLUS}" -S "system@localhost:1521/${ORACLE_SERVICE}" @"${SETUP_SQL}" \
    && echo "    DB setup OK" \
    || echo "    DB setup FAILED — run ${SETUP_SQL} manually in SQL Developer as SYSTEM"
else
  echo "    sqlplus not found — run this file in SQL Developer as SYSTEM@${ORACLE_SERVICE}:"
  echo "    ${SETUP_SQL}"
fi

# --- 5) Firewall ---
echo "[5] Opening ports 1521 and ${API_PORT}..."
if command -v firewall-cmd &>/dev/null; then
  sudo firewall-cmd --add-port=1521/tcp --permanent 2>/dev/null || true
  sudo firewall-cmd --add-port=${API_PORT}/tcp --permanent 2>/dev/null || true
  sudo firewall-cmd --reload 2>/dev/null || true
fi

# --- 6) Stop old app ---
echo "[6] Stopping old pkc-api processes..."
pkill -f "pkc-api.jar" 2>/dev/null || true
sleep 2

# --- 7) Start app ---
echo "[7] Starting pkc-api.jar..."
export SPRING_PROFILES_ACTIVE=oracle
export ORACLE_JDBC_URL="${ORACLE_JDBC_URL}"
export ORACLE_USER="${ORACLE_USER}"
export ORACLE_PASSWORD="${ORACLE_PASSWORD}"

cd "${HOME_DIR}"
nohup java -Dspring.profiles.active=oracle -jar "${JAR}" > "${LOG}" 2>&1 &
APP_PID=$!
echo "    PID: ${APP_PID}"
echo "    Log: ${LOG}"

# --- 8) Wait for startup ---
echo "[8] Waiting for port ${API_PORT}..."
for i in $(seq 1 30); do
  if ss -tlnp 2>/dev/null | grep -q ":${API_PORT} "; then
    echo "    Port ${API_PORT} is OPEN"
    break
  fi
  if ! kill -0 "${APP_PID}" 2>/dev/null; then
    echo "    Process died. Last log lines:"
    tail -40 "${LOG}"
    exit 1
  fi
  sleep 2
done

if ! ss -tlnp 2>/dev/null | grep -q ":${API_PORT} "; then
  echo "    Port ${API_PORT} still closed. Log:"
  tail -50 "${LOG}"
  echo ""
  echo "    If you see ORA-01045 or ORA-01017: fix DB with ${SETUP_SQL}"
  echo "    If ORA-12514: try: ORACLE_SERVICE=FREEPDB1 bash $0"
  exit 1
fi

# --- 9) Test API ---
echo "[9] Testing API..."
curl -sf "http://localhost:${API_PORT}/convert-measurements?input=aa" && echo ""
curl -sf "http://localhost:${API_PORT}/history" | head -c 500 && echo ""

echo ""
echo "=============================================="
echo " DONE — API is running on Oracle Linux"
echo "=============================================="
echo " VM test:  curl http://localhost:${API_PORT}/convert-measurements?input=aa"
echo " Table:    PKC_USER.MEASUREMENT_HISTORY"
echo ""
echo " DbVisualizer on Mac (set VirtualBox port forward 1521 first):"
echo "   URL:      jdbc:oracle:thin:@//127.0.0.1:1521/${ORACLE_SERVICE}"
echo "   User:     ${ORACLE_USER}"
echo "   Password: ${ORACLE_PASSWORD}"
echo "   Tree:     PKC_USER -> Tables -> MEASUREMENT_HISTORY"
echo "=============================================="
