-- =============================================================================
-- Run ON ORACLE LINUX (as SYSTEM) — SQL*Plus or SQL Developer on the VM
-- Service: XEPDB1  (or FREEPDB1 for Oracle 23c Free — change below)
-- Creates: user PKC_USER + table MEASUREMENT_HISTORY (your program data)
-- =============================================================================

ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER pkc_user CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1918, -01918) THEN
      RAISE;
    END IF;
END;
/

CREATE USER pkc_user IDENTIFIED BY PkcPassword1
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CONNECT, RESOURCE TO pkc_user;
GRANT CREATE TABLE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO pkc_user;

ALTER SESSION SET CURRENT_SCHEMA = pkc_user;

-- Your application's history table (Hibernate also maintains this)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE measurement_history CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE measurement_history (
    id                  NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp           TIMESTAMP     NOT NULL,
    source_ip_address   VARCHAR2(255) NOT NULL,
    input_value         VARCHAR2(4000) NOT NULL,
    output_value        VARCHAR2(4000) NOT NULL
);

COMMENT ON TABLE measurement_history IS 'Package conversion API request history (pkc-api)';

SELECT 'User OK' AS step, username, account_status
FROM dba_users WHERE username = 'PKC_USER';

SELECT 'Privileges' AS step, privilege
FROM dba_sys_privs WHERE grantee = 'PKC_USER' ORDER BY privilege;

SELECT 'Table OK' AS step, table_name
FROM all_tables
WHERE owner = 'PKC_USER' AND table_name = 'MEASUREMENT_HISTORY';

COMMIT;
